<?php

/**
 * Default English Lexicon Entries for Twilio
 *
 * @package twilio
 * @subpackage lexicon
 */

$_lang['twilio'] = 'Twilio';
$_lang['twilio.submit'] = 'Submit';
$_lang['twilio.verifying'] = 'Verifying...';
$_lang['twilio.qrcode'] = 'Authentication QR Code';

$_lang['twilio.2fa'] = 'Two-Factor Authentication';
$_lang['twilio.2fa.code'] = 'Enter Code';
$_lang['twilio.2fa.email'] = 'Email Code';
$_lang['twilio.2fa.verify_msg'] = 'For first time setup, please verify the code generated by your authentication app.';
$_lang['twilio.2fa.challenge_msg'] = 'Please enter the code generated by your authentication app.';
// Settings
$_lang['setting_twilio.account_sid'] = 'Account SID';
$_lang['setting_twilio.account_sid_desc'] = 'Found under Account Info here https://console.twilio.com/';
$_lang['setting_twilio.account_token'] = 'Account Auth Token';
$_lang['setting_twilio.account_token_desc'] = 'Found under Account Info here https://console.twilio.com/';
$_lang['setting_twilio.service_id'] = 'Service ID';
$_lang['setting_twilio.service_id_desc'] = 'Found under Services Page here https://console.twilio.com/us1/develop/verify/services';
