<?php

/**
 * Default English Lexicon Entries for Twilio
 *
 * @package twilio
 * @subpackage lexicon
 */

$_lang['twilio'] = 'Twilio';
$_lang['twilio.submit'] = 'Submit';
$_lang['twilio.verifying'] = 'Verifying...';
$_lang['twilio.qrcode'] = 'Authentication QR Code';
//2fa
$_lang['twilio.2fa'] = 'Two-Factor Authentication';
$_lang['twilio.2fa.code'] = 'Enter Code';
$_lang['twilio.2fa.email'] = 'Email Code';
$_lang['twilio.2fa.verify_msg'] = 'For first time setup, please verify the code generated by your authentication app.';
$_lang['twilio.2fa.challenge_msg'] = 'Please enter the code generated by your authentication app.';
//Users
$_lang['twilio.users'] = 'User Authentication';
$_lang['twilio.users.desc'] = 'Manage the authentication status of MODX users.';
$_lang['twilio.users.username'] = 'Username';
$_lang['twilio.users.fullname'] = 'Full Name';
$_lang['twilio.users.email'] = 'Email';
$_lang['twilio.users.totp_status'] = '2FA Status';
$_lang['twilio.users.totp_value'] = 'Use 2FA';
$_lang['twilio.users.enable_totp'] = 'Enable 2FA';
$_lang['twilio.users.disable_totp'] = 'Disable 2FA';
$_lang['twilio.users.create_totp'] = 'Create 2FA Code';
$_lang['twilio.users.clear_totp'] = 'Clear 2FA';
$_lang['twilio.users.reset_totp'] = 'Reset 2FA Code';
$_lang['twilio.users.email_totp'] = 'Email 2FA Code';
$_lang['twilio.users.totp_status_'] = 'Unknown';
$_lang['twilio.users.totp_status_null'] = 'N/A';
$_lang['twilio.users.totp_status_not_set'] = 'Not Set';
$_lang['twilio.users.totp_status_verified'] = 'Verified';
$_lang['twilio.users.totp_status_unverified'] = 'Awaiting Verification';
$_lang['twilio.users.with-selected'] = 'With Selected';
// Settings
$_lang['setting_twilio.account_sid'] = 'Account SID';
$_lang['setting_twilio.account_sid_desc'] = 'Found under Account Info here https://console.twilio.com/';
$_lang['setting_twilio.account_token'] = 'Account Auth Token';
$_lang['setting_twilio.account_token_desc'] = 'Found under Account Info here https://console.twilio.com/';
$_lang['setting_twilio.service_id'] = 'Service ID';
$_lang['setting_twilio.service_id_desc'] = 'Found under Services Page here https://console.twilio.com/us1/develop/verify/services';
$_lang['setting_twilio.totp_enforce'] = 'Enforce Two-Factor Authentication on Login';
$_lang['setting_twilio.totp_email_on_login'] = 'Email Two-Factor Authentication Code on Login (requires sha-1 encryption)';
$_lang['setting_twilio.totp_challenge_page'] = 'Two-Factor Authentication Challenge Resource ID';
